%YAML:1.0

system.baudrate: 921600
system.uart_name: /dev/ttySAC0
system.vocabulary: /home/rasp/CLionProjects/LearnVI_Drone/Vocabulary/ORBvoc.txt
system.setting: /home/rasp/CLionProjects/LearnVI_Drone/config/mobius.yaml
system.mode: LIVERECORD
system.gui: ENABLE
system.record_path: /home/rasp/CLionProjects/LearnVI_Drone
system.fps: 10
system.mission_route: /home/rasp/CLionProjects/LearnVI_Drone/mission_route.txt
system.camera1: 0
system.camera2: 1
