%YAML:1.0

system.baudrate: 921600
system.uart_name: /dev/ttyUSB0
system.mode: OFFLINE
system.gui: ENABLE
system.vocabulary: /home/rasp/CLionProjects/LearnVI_Drone/Vocabulary/ORBvoc.txt

system.setting: /home/rasp/CLionProjects/LearnVI_Drone/config/euroc.yaml
#system.setting: /home/rasp/CLionProjects/LearnVI_Drone/config/mobius.yaml

#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/MH_01_easy_extract
system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/MH_02_easy_extract
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/MH_03_medium_extract
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/MH_04_difficult_extract
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/V1_01_easy
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/V1_02_medium_extract
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/kalibr_set5
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/offline
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/set1-livingroom
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/set2-livingroom
#system.record_path: /home/rasp/CLionProjects/LearnVI_Drone/download_result/set3-roadwithshadow

system.fps: 10
system.mission_route: /home/rasp/CLionProjects/LearnVI_Drone/mission_route2.txt
system.camera1: 1
system.camera2: -1
